### ISSUE TITLE
感谢您的工作！想问一下LPS、SPC和SPA具体在代码中是如何实现的

### ISSUE THREAD

**Issue by SUZILI7** [CrossmodalGroup/LAPS#3]
这几个分别对应的是TokenSparse类，TokenAggregation类和CrossSparseAggrNet_v2类吗

**Comment by darkpromise98** [comment]
You're basically right.

LPS (patch selection) is for `class TokenSparse`  
https://github.com/CrossmodalGroup/LAPS/blob/main/lib/cross_net.py#L14

SPC (patch calibration/aggregation) is for `class TokenAggregation ` 
https://github.com/CrossmodalGroup/LAPS/blob/main/lib/cross_net.py#L61

SPA (patch-word alignment) is for `def mask_xattn_one_text` 
https://github.com/CrossmodalGroup/LAPS/blob/main/lib/cross_net.py#L203
https://github.com/CrossmodalGroup/LAPS/blob/main/lib/xttn.py#L225

**Comment by SUZILI7** [comment]
非常感谢！
