### ISSUE TITLE
您好，请问一下您在CLIP上进行微调，使用的CLIP权重链接可以公布一下吗？

### ISSUE THREAD

**Issue by lhqxcc** [CrossmodalGroup/LAPS#5]

**Comment by darkpromise98** [comment]
The original CLIP weights come from the official repositories:
https://huggingface.co/openai/clip-vit-large-patch14
https://huggingface.co/openai/clip-vit-base-patch16

The release plan for fine-tuned weights is not included in this repository.

**Comment by lhqxcc** [comment]
好的，十分感谢您的解答！
