### ISSUE TITLE
随机种子设置问题

### ISSUE THREAD

**Issue by lhqxcc** [CrossmodalGroup/LAPS#6]
您好，十分感谢您的出色工作！想请问一下您的代码中随机种子设置的相关代码被注释了，对每次跑出来的结果影响大吗？

**Comment by darkpromise98** [comment]
使用不同随机种子，在 ViT encoder + Flickr dataset上的实验结果会有比较大的波动（rSum ± 4），因为ViT encoder表征能力较差，且Flickr数据集较小，所以实验结果相对没那么稳定。  相对地，在使用Swin encoder或在MSCOCO dataset上的实验结果不会有太大波动（因为Swin Transformer表征能力更强，MSCOCO数据集更大）。

**Comment by lhqxcc** [comment]
好的，十分感谢您的解答！
